### ISSUE TITLE
Bug (was already in Noel's code)

### ISSUE THREAD

**Issue by PirminR** [luuksommers/MapiEx#2]
MAPIFolder.cpp
253:  `if(m_pRows==NULL || m_nRowsIndex>=m_pRows->cRows)`

m_nRowsIndex should be lower then the rowcount (m_pRows->cRows). Equal is already one item above
-> `if (m_pRows == NULL || m_nRowsIndex > m_pRows->cRows)`

**Comment by luuksommers** [comment]
How did you notice this error? 

When I look at the code, the ` m_nRowsIndex` is 0 based, so when for example, there are 5 rows, and the `m_nRowsIndex` is also 5, the next row should return NULL. So the question would be: Should `QueryRows()` be called when this happens, or should we just return NULL.

**Comment by PirminR** [comment]
`QueryRows()` should be called (and MUST to call `ClearBuffer()`) , because otherwise the 262: `return &m_pRows->aRow[m_nRowsIndex++];` points to (in your case of 5 Items) to a not existing item (5) in the aRow-Array (5 Items with index 0 to 4)

**Comment by PirminR** [comment]
Sorry, you were right - greater and equal is already above the max-index - my fault!

**Comment by PirminR** [comment]
...closed...
