### ISSUE TITLE
How to open a .msg file from disk as a MAPIMessage ?

### ISSUE THREAD

**Issue by toxnico** [luuksommers/MapiEx#3]
Hello Luuk,

I discovered your library today because I need to do some extended MAPI from C#.

Actually I need to:

1. Open a .msg file from hard drive, and get a MAPIMessage or MAPIObject
2. Call SetMessageFlags() on it
3. Save back to the original file (or another file, I don't really care)

I cannot figure out how to open a msg file from disk. Is it possible to do this with MapiEx?

Thanks!

Nico

**Comment by luuksommers** [comment]
Hi Nico,

I don't think that is possible with the current code. If you look into: https://stackoverflow.com/questions/26633082/read-outlook-msg-file you'll see that there is a [MsgReader](https://www.nuget.org/packages/MSGReader/) [(code)](https://github.com/Sicos1977/MSGReader) that can already read .msg files, or the commercially available [MSG .NET](http://www.independentsoft.de/msg/) which does exactly what you want.

I guess it is possible to add support for read / write .msg files from disk (it's mapi after all), I warmly welcome any pull requests to this repository to extend the functionality.

Best of luck finding the appropriate solution!

**Comment by toxnico** [comment]
Hi Luuk,

Thanks for answering so fast! And thank you very much for these interesting suggestions!
If I finally make something that can extend MapiEx, I will of course send you a PR :)

Cheers,

Nico

**Comment by luuksommers** [comment]
No problem, I'll close this issue for now. If you have any suggestions of questions concerning this library, feel free to ask.
